// Generated by package-runtime.py; separate from the unchanged source catalog.
export const corridorBuildingPackIndexSha256 = '5a616693fa4744f970408138dfff7ab739642e5e75125148509488ad2b8e3777';
export const corridorBuildingPackIndexUrl = '/models/osm2world/hudson/buildings.pack.index.json';
export const corridorBuildingPackSha256 = '4cd4c0b455ef3395e7fcfc0a5f27c0b115d5a3dc93a2d3c864bfb3c7cf719374';
